# Makefile para Certamen 3 - Lenguajes de Programación

run:
	@echo "[PASO 1] Indexacion"
	awk -f indexador.awk dataset.csv > index_raw.txt
	
	@echo "\n[PASO 2] Eliminando stopwords (Python Recursivo)..."
	python limpiador.py
	
	@echo "\n[PASO 3] Iniciando Buscador..."
	python buscador.py

clean:
	# Limpia los archivos generados
	del index_raw.txt index_master.txt